export const GamePhase = {
    PLAYER_TURN: 'PLAYER_TURN',
    VILLAIN_STEP_1_THREAT: 'VILLAIN_STEP_1_THREAT',
    VILLAIN_STEP_2_ACTIVATION: 'VILLAIN_STEP_2_ACTIVATION',
    VILLAIN_STEP_3_MINIONS: 'VILLAIN_STEP_3_MINIONS',
    VILLAIN_STEP_4_DEAL: 'VILLAIN_STEP_4_DEAL',
    VILLAIN_STEP_5_REVEAL: 'VILLAIN_STEP_5_REVEAL'
} as const;

export type GamePhaseType = typeof GamePhase[keyof typeof GamePhase];
